-- -----------------------------------------------------
-- Books
-- -----------------------------------------------------

INSERT INTO book (title, author, publisher, publication_date, language, category, number_of_pages, format, isbn, shipping_weight, list_price, our_price, active, description, in_stock_number, book_image) VALUES 
	('Java: A Beginners Guide, Sixth Edition', 'Herbert Schildt', 'Pocket Books', '2011-12-27', 'english', 'Programming', 1168, 'paperback', 1439189293, 19.99, 104.06, 95.95, 1,'Fully updated for Java Platform, Standard Edition 11, Java SE 11, Java: A Beginners Guide, Eighth Edition gets you started programming in Java right away. Best-selling programming author Herb Schildt begins with the basics, such as how to create, compile, and run a Java program. He then moves on to the keywords, syntax, and constructs that form the core of the Java language. The book also covers some of Javas more advanced features, including multithreaded programming, generics, lambda expressions, modules, and Swing. As an added bonus, an introduction to JShell, Javas interactive programming tool, is included. Best of all, it’s written in the clear, crisp, uncompromising style that has made Schildt the choice of millions worldwide.', 5, 'https://m.media-amazon.com/images/I/51KDndebj7L._SX403_BO1,204,203,200_.jpg		'),
	('Ordinary Grace', 'William Kent Krueger', 'Pocket Books', '2011-12-27', 'english', 'Fiction', 1168, 'paperback', 1439189293, 19.99, 34.06, 22.95, 1,'Dr. Benjamin Spock is Americas most trusted name in child care and parenting, and his essential guidebook has topped bestseller lists for over sixty-five years. This fully revised and updated edition of the classic manual provides first time and experienced parents the best information about caring for new babies, toddlers, and adolescents in the twenty-first century.', 5, 'https://m.media-amazon.com/images/I/51Lck4MddFL._SX320_BO1,204,203,200_.jpg'),
	('Practical Electronics for Inventors, Fourth Edition', 'Paul Scherz', 'McGraw-Hill Education TAB', '2016-03-24', 'english', 'Engineering', 1168, 'paperback', 1439189293, 19.99, 124.06, 100.95, 1,'Advance your electronics knowledge and gain the skills necessary to develop and construct your own functioning gadgets. Written by a pair of experienced engineers and dedicated hobbyists, Practical Electronics for Inventors, Fourth Edition, lays out the essentials and provides step by step instructions, schematics, and illustrations. Discover how to select the right components, design and build circuits, use microcontrollers and ICs, work with the latest software tools, and test and tweak your creations. This easy to follow book features new instruction on programmable logic, semiconductors, operational amplifiers, voltage regulators, power supplies, digital electronics, and more.', 5, 'https://m.media-amazon.com/images/I/51SXFRufPJL._SX385_BO1,204,203,200_.jpg'),
	('The 27 Challenges Managers Face: Step-by-Step Solutions to (Nearly) All of Your Management Problems', 'Bruce Tulgan', 'Jossey-Bass', '2014-09-09', 'english', 'Management', 32, 'hardcover', 111872559, 16.95, 32.95, 22.55, 1, 'For more than twenty years, management expert Bruce Tulgan has been asking, What are the most difficult challenges you face when it comes to managing people? Regardless of industry or job title, managers cite the same core issues―27 recurring challenges: the superstar whom the manager is afraid of losing, the slacker whom the manager cannot figure out how to motivate, the one with an attitude problem, and the two who cannot get along, to name just a few. It turns out that when things are going wrong in a management relationship, the common denominator is almost always unstructured, low substance, hit-or-miss communication. The real problem is that most managers are managing on autopilot without even realizing it―until something goes wrong. And if you are managin	g on autopilot, then something almost always does. The 27 Challenges Managers Face shows exactly how to break the vicious cycle and gain control of management relationships. No matter what the issue, Tulgan shows that the fundamentals are all you need. The very best managers hold ongoing one-on-one conversations that make expectations clear, track performance, offer feedback, and hold people accountable. For every workplace problem―even the most awkward and difficult―The 27 Challenges Managers Face shows how to tailor conversations to solve situations familiar to every manager. Tulgan offers clear approaches for turning around bad attitudes, reducing friction and conflict, improving low performers, retaining top performers, and even addressing your own personal burnout. The 27 Challenges Managers Face is an indispensable resource for managers at all levels, one anyone managing anyone will want to keep on hand. One challenge at a time, you will see how the most effective managers use 		the fundamentals of management to proactively resolve (nearly) any problem a manager could face.', 2, 'https://m.media-amazon.com/images/I/51YXJs7Fe3L._SX333_BO1,204,203,200_.jpg'),
	('How to Win Friends & Influence People', 'Dale Carnegie', 'Pocket Books', '1998-10-01', 'english', 'Management', 54, 'paperback', 671027034, 16.95, 10.95, 7.55, 1, 'You can go after the job you want—and get it!
	You can take the job you have—and improve it! You can take any situation—and make it work for you! Dale Carnegies rock-solid, time-tested advice has carried countless people up the ladder of success in their business and personal lives. One of the most groundbreaking and timeless bestsellers of all time, How to Win Friends & Influence People will teach you:
	Six ways to make people like you. Twelve ways to win people to your way of thinking. Nine ways to change people without arousing resentment And much more! Achieve your maximum potential—a must-read for the twenty-first century with more than 15 million copies sold!', 7, 'https://m.media-amazon.com/images/I/41OksZQYt+L._SY344_BO1,204,203,200_.jpg'),	
	('The First-Time Manager', 'Loren B. Belker', 'AMACOM', '2012-01-03', 'english', 'Management', 47, 'paperback', 814417833, 17.51, 61.95, 50.50, 1, 'Whats a rookie manager to do? Faced with new responsibilities, and in need of quick, dependable guidance, novice managers cant afford to learn by trial and error. The First-Time Manager is the answer, dispensing the bottom-line wisdom they need to succeed. A true management classic, the book covers essential topics such as hiring and firing, leadership, motivation, managing time, dealing with superiors, and much more. Written in an inviting and accessible style, the revised sixth edition includes new material on increasing employee engagement, encouraging innovation and initiative, helping team members optimize their talents, improving outcomes, and distinguishing oneself as a leader. Packed with immediately usable insight on everything from building a team environment to conducting performance appraisals, The First-Time Manager remains th	e ultimate guide for anyone starting his or her career in management.', 14, 'https://m.media-amazon.com/images/I/51J1hNL5DNL._SX331_BO1,204,203,200_.jpg'),
	('Your Inner Critic Is a Big Jerk: And Other Truths About Being Creative', 'Danielle Krysa', 'Chronicle Books', '2016-10-11', 'english', 'Arts & Literature', 65, 'hardcover', 1452148449, 16.95, 16.95, 12.55, 1, 'This book is duct tape for the mouth of every artists inner critic. Silencing that stifling voice once and for all, this salve for creatives introduces ten truths they must face in order to defeat self-doubt. Each encouraging chapter deconstructs a pivotal moment on the path to success--fear of the blank page, the dangers of jealousy, sharing work with others--and explains how to navigate roadblock. Packed with helpful anecdotes, thoughts from successful creatives, and practical exercises gleaned from Danielle Krysa years of working with professional and aspiring artists--plus riotously apt illustrations from art world darling Martha Rich--this book arms readers with the most essential tool for their toolbox: the confidence they need to get down to business and make good work		.', 14, 'https://m.media-amazon.com/images/I/410XA3ppmOL.jpg'),
	('Dr. Spocks Baby and Child Care: 9th Edition 1', 'Benjamin Spock M.D.', 'Pocket Books', '2011-12-27', 'english', 'Arts & Literature', 1168, 'paperback', 1439189293, 19.99, 234.06, 200.95, 1,'Dr. Benjamin Spock is Americas most trusted name in child care and parenting, and his essential guidebook has topped bestseller lists for over sixty-five years. This fully revised and updated edition of the classic manual provides first time and experienced parents the best information about caring for new babies, toddlers, and adolescents in the twenty-first century.', 5, 'https://m.media-amazon.com/images/I/41nCXFzArSL._SX309_BO1,204,203,200_.jpg'),
	('Leonardos Notebooks: Writing and Art of the Great Master', 'Leonardo Da Vinci', 'Black Dog & Leventhal', '2013-09-24', 'english', 'Arts & Literature', 448, 'paperback', 1579129463, 19.99, 34.06, 20, 1,'Leonardo da Vinci -- artist, inventor, and prototypical Renaissance man -- is a perennial source of fascination. His astonishing intellect and boundless curiosity about both the natural and man-made world influenced his numerous works of art, theories, and sentiments -- all of which were kept in his voluminous notebooks. This book is a collection of da Vinci intricately detailed artistic and intellectual pursuits, and highlights the classic pieces of art he produced in connection with his writings. Leonardos Notebooks provides a fascinating look into da Vinci most private world, and sorts his wide range of interests into subjects such as human figures, light and shade, perspective and visual perception, anatomy, botany and landscape, geography, the physical sciences and astronomy, arc	hitecture, inventions and so much more. Exploring this image-filled book is as close to reading da Vinci diaries as we can get. Organized and curated by art historian H. Anna Suh, she provides fascinating commentary and insight into the material, making Leonardos Notebooks an exquisite single-volume compendium celebrating his enduring brilliance.', 7, 'https://m.media-amazon.com/images/I/51yCxCAQ-yL._SX373_BO1,204,203,200_.jpg'),
	('Miles Davis for Solo Guitar', 'Miles Davis', 'Hal Leonard', '2006-02-01', 'english', 'Arts & Literature', 96, 'paperback', 634023020, 17.51, 21.95, 15, 1,'<p><span style=\"color: #333333; font-family: Arial, sans-serif;\">(Guitar Solo). 15 jazzy solo guitar arrangements of Davis classics, including: All Blues * All of You * Blue in Green * Bye Bye Blackbird * Four * Freddie Freeloader * I Could Write a Book * Milestones * Nardis * Nefertiti * Seven Steps to Heaven * So What * Solar * There Is No Greater Love * When I Fall in Love. The CD includes full demos of each piece by Jamie Findlay.</span></p>', 10, 'https://m.media-amazon.com/images/I/51rtjLQ044L._SX373_BO1,204,203,200_.jpg');






